---
title: "Overview"
format: html
---

## Clinical background

HIV SLK

## What this analysis does

This project uses the [**Scientific Registry of Transplant Recipients**]() to analyze HIV.



## Methods

Matchin

## Results

Pending

## Site navigation

-   [**Setup**](quarto/setup.qmd): Defines global paths, data sources, cohort inclusion criteria, and analysis-wide constants.
-   [**Functions**](quarto/functions.qmd): Reusable helper functions for cohort construction, matching, costing, and modeling.
-   [**About**](quarto/about.qmd): methods, assumptions, and disclosures



### Reproducibility

All analyses presented on this website are fully reproducible.  

The complete source code used to perform the full analysis and generate the tables and figures is publicly available at this [GitHub repo](https://github.com/VagishHemmige/HIV-SLK-outcomes).  The R script `R/main.R` will run the R subscripts needed for this analysis in the order they are to be run.  Model assumptions, parameter values, and analytic workflows are documented in the repository to facilitate transparency and reuse.


## Abstracts/manuscripts

This analysis has yet to be published to date.

